#!/bin/bash -e

case ${1} in

    configure)

  #Luego que se instala la aplicacion se reinicia el nginx
  service nginx restart || true 
  

    ;;

        abort-upgrade|abort-remove|abort-deconfigure)

        ;;

        *)

                echo "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

exit 0