#!/bin/bash -e

case ${1} in

    install|upgrade)

  #Si el servicio de apache esta activo lo detenemos para poner correr el server de nginx
  service apache2 stop || true 

    ;;

    abort-upgrade|abort-install)

    ;;

    *)
            echo "preinst no reconoce el argumento '"${1}"'" >&2
            exit 1
    ;;

esac

#DEBHELPER#

exit 0