#!/bin/bash -e


case ${1} in

    remove|upgrade|deconfigure)

    #Detenemos el servicio de nginx para que la aplicacion pueda ser eliminada
    service nginx stop

    ;;

    failed-upgrade)

    ;;

    *)

        echo "prerm no reconoce el argumento '"${1}"'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0