# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0008_auto_20180417_1316'),
        ('evaluacion', '0002_auto_20180413_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('tipo_llave', models.CharField(blank=True, max_length=50)),
                ('observacion2', models.CharField(blank=True, max_length=255)),
                ('contenido_repo', models.CharField(blank=True, choices=[('PA', 'Paquete'), ('CF', 'Codigo-Fuente'), ('OT', 'Otro')], max_length=2)),
                ('cantidad_paquete', models.CharField(blank=True, max_length=50)),
                ('cantidad_codigo', models.CharField(blank=True, max_length=50)),
                ('cantidad_otro', models.CharField(blank=True, max_length=50)),
                ('observacion3', models.CharField(blank=True, max_length=255)),
                ('despcricion4', models.TextField(blank=True, max_length=1000)),
                ('despcricion5', models.TextField(blank=True, max_length=1000)),
                ('readme', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('otro_doc', models.CharField(blank=True, max_length=100)),
                ('tipo_doc', models.CharField(blank=True, choices=[('USU', 'Usuario'), ('DEV', 'Desarrollador'), ('OTO', 'Otro')], max_length=3)),
                ('usu_usuario_check', models.BooleanField(default=False)),
                ('usu_descripcion_check', models.BooleanField(default=False)),
                ('dev_doc_ejecucion', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('lenguaje_programacion', models.CharField(blank=True, max_length=200)),
                ('dependecia_adicional', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('dependecia_adicional_descripcion', models.CharField(blank=True, max_length=255)),
                ('manual_usuario', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No'), ('OT', 'Otro')], max_length=2)),
                ('observacion6', models.CharField(blank=True, max_length=255)),
                ('comando_mal', models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=2)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('rama_desarrollo', models.CharField(blank=True, choices=[('main', 'Main'), ('contrib', 'Contrib'), ('non-free', 'Non-free')], max_length=8)),
                ('observacion8', models.CharField(blank=True, max_length=255)),
                ('datos_paquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postulacion.Package')),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='datos_paquete',
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
