# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_auto_20180417_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camposevaluacion',
            old_name='cantidad_codigo',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='camposevaluacion',
            name='cantidad_otro',
        ),
        migrations.RemoveField(
            model_name='camposevaluacion',
            name='cantidad_paquete',
        ),
    ]
