# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0002_auto_20180402_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='usuario',
            field=models.CharField(max_length=200, verbose_name='Nombre del Usuario'),
        ),
    ]
