# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0003_auto_20180402_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='usuario',
            field=models.CharField(max_length=200),
        ),
    ]
