# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0006_auto_20180403_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description_package',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
