# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulacion', '0007_auto_20180413_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description_package',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
