# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_package', models.CharField(max_length=50, verbose_name='Nombre del Paquete')),
                ('fecha_actualizada', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Postulado', 'Postulado'), ('En Evaluacion', 'En Evaluacion'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='En Evaluacion', max_length=10)),
            ],
            options={
                'ordering': ('fecha_actualizada',),
            },
        ),
        migrations.CreateModel(
            name='ObsEvaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('obs1', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs2', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs3', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs4', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs5', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs6', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs7', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs8', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('obs9', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='PreEvaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('pre1', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre2', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre3', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre4', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre5', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre6', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre7', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
                ('pre8_0', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=7, verbose_name='main')),
                ('pre8_1', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=7, verbose_name='contrib')),
                ('pre8_2', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=7, verbose_name='non-free')),
                ('pre9', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, max_length=5)),
            ],
        ),
    ]
