# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusSeguimiento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObsEvaluador',
        ),
        migrations.DeleteModel(
            name='PreEvaluador',
        ),
    ]
